name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - uses: bahmutov/npm-install@v1

    - name: Pre-generate docs
      run: yarn run pregenerate

    - name: Run linter
      run: yarn run lint
